name       : kwindowsystem
version    : 5.71.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kwindowsystem-5.71.0.tar.xz : a3613aea6fa73ebc53f28c011a6bca31ed157e29f85df767e617c44399360cda
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xfixes)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
