name       : kwindowsystem
version    : 5.82.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/kwindowsystem-5.82.0.tar.xz : 6a80e662bc598a69cd32651ce11b501ac903bb8729f4fd45915edf5d270a790e
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xfixes)
    - pkgconfig(xrender)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
