name       : kwindowsystem
version    : 5.51.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kwindowsystem-5.51.0.tar.xz : a1f7ab4e1040d360b6627570d4d6bb88555e4d66cec794ce4405f71c046c81c2
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
