name       : kwindowsystem
version    : 5.36.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.36/kwindowsystem-5.36.0.tar.xz : 8a1991e36ed74daa2085ea936d26adf59edd11d7d5c08a9b721a670a21821172
license    : LGPL-2.1
component  : programming
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
