name       : kwindowsystem
version    : 5.72.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/kwindowsystem-5.72.0.tar.xz : b4c4a682d467247a8e3397487a2a4c773fa91dd587cc1f4ddc6350891af12a3f
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xfixes)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
