name       : kwindowsystem
version    : 5.39.0
release    : 8
source     :
    - https://download.kde.org/stable/frameworks/5.39/kwindowsystem-5.39.0.tar.xz : 17771aa0acf93b32329633aac9b07e72448edee2a2ecfe7a8f0040a23638dab7
license    : LGPL-2.1
component  : programming
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
