name       : kwindowsystem
version    : 5.44.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kwindowsystem-5.44.0.tar.xz : 1e6f7b6298c244b4c2e0b6c3224ef7a6da2391a2144a53d63e3906ec0113c062
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
