name       : kwindowsystem
version    : 5.67.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kwindowsystem-5.67.0.tar.xz : 6ec04272ef5beb4e10ef9af65d10b10df454ce7fe00534fa6f807246c2ba24fe
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
