name       : kwindowsystem
version    : 5.47.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/kwindowsystem-5.47.0.tar.xz : a673722d2dc8a0dd302cb5dad3e2069244af0918fc0f3508313c9a758297cbc1
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
