name       : kwindowsystem
version    : 5.85.0
release    : 56
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/kwindowsystem-5.85.0.tar.xz : 6db43758f1508d30d840623b6c505aa3c8d326dd8fa60c9e9cdcd1feb469661e
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xfixes)
    - pkgconfig(xrender)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
