name       : kwindowsystem
version    : 5.52.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kwindowsystem-5.52.0.tar.xz : fd7adee58e803732cda7ea1ba1d99f6750920a774945293174e0512254bdaeab
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
