name       : kwindowsystem
version    : 5.62.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/kwindowsystem-5.62.0.tar.xz : 116d75216ea001b2fc8688a72bcc6105b0b0966a2c5a084497f3aef80d158a67
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
