name       : kwindowsystem
version    : 5.48.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/kwindowsystem-5.48.0.tar.xz : 369d42e8c7aae5dd1cbc8fe6c039ec28c90a8320da1f2fa2dc154fec47dfccac
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
