name       : kwindowsystem
version    : 5.53.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kwindowsystem-5.53.0.tar.xz : 9fb2009a1915167e243d4182a5cf8932bfe416b31a2f13f06256f3e1eb5809fd
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
