name       : kwindowsystem
version    : 5.55.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kwindowsystem-5.55.0.tar.xz : a698ddf3caeb890314b3b768a15b4cc35dd9e10356af4cf9faa89c8640eded83
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
