name       : kwindowsystem
version    : 5.74.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kwindowsystem-5.74.0.tar.xz : 33da54b0f76a661919445c9352c04cc23f9b6a0f4c842a76aa810091ca09b12f
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xfixes)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
