name       : kwindowsystem
version    : 5.60.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kwindowsystem-5.60.0.tar.xz : 3bdce23b75b4b1d1eea69fb2035ff5be94ea2c1b7bb3d4e529a9b1740b106315
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
