name       : kwindowsystem
version    : 5.28.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.28/kwindowsystem-5.28.0.tar.xz : 71e4a59371e3ef11f8cb91d2372c43fe182c7984996fcbd82eefa1227974ea53
license    : LGPL-2.1
component  : programming
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
