name       : kwindowsystem
version    : 5.59.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kwindowsystem-5.59.0.tar.xz : 6c51e7f24be7323caad08bd3ebea2fd941c1b185e9cd2c740a2b887eac98e1e3
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
