name       : kwindowsystem
version    : 5.46.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/kwindowsystem-5.46.0.tar.xz : a34f63180eb771de5f83e3dc09a31cba1c9708281657d0afd6787629398ab067
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
