name       : kwindowsystem
version    : 5.77.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/kwindowsystem-5.77.0.tar.xz : 064d31310a8568fb1900c19b955176e245d96f0b42061c15c20bc2e2a7ab4f82
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xfixes)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
