name       : kwindowsystem
version    : 5.75.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/kwindowsystem-5.75.0.tar.xz : 4c180ec41aad90ed83e97db72216913e650b2719946803eec0d6e4cee7aab743
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xfixes)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
