name       : kwindowsystem
version    : 5.100.0
release    : 68
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/kwindowsystem-5.100.0.tar.xz : 69b24ebaa5c94aa040c46dc1270a8fc9e44ed35d497c16b9b3244bb200834fb3
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.1-only
    - LGPL-2.1-or-later
    - MIT
component  : programming.library
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xfixes)
    - pkgconfig(xrender)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
        - libx11-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
