name       : kwindowsystem
version    : 5.43.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/kwindowsystem-5.43.0.tar.xz : 4df6da4f313f8c52a5d202caa5cc90791b4a07f0d91d5b7252e2da5487a6997d
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Access to the windowing system.
description: |
    Access to the windowing system.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xrender)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
